import React from "react";
import Styles from "../styles/About.module.scss";
import Image from "next/image";
import Head from "next/head";

const About = ({}) => {
  return (
    <>
    <Head>
     <title>About Page</title>
     <meta name="description" content="Generated by create next app" />
    </Head>
    <div className="bg-info">
      <h2 className={Styles.about_text}> This is About file</h2>
      <Image src="/11.jpg" height={300} width={400} />
    </div>
    </>
  );
};

export default About;
